server:
  port: 8082
  tomcat:
    uri-encoding: UTF-8
spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    #url: jdbc:oracle:thin:@192.135.8.190:1521:topsd
    #username: geps
    #password: passw0rd
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: evan
    password: 123
    #schema: classpath:schema.sql
    #data: classpath:data.sql
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  messages:
    encoding: UTF-8
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    cache: false
  resources:
    static-locations: classpath:/static/
  jpa:
    show-sql: false
    hibernate:
#      ddl-auto: create
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.Oracle10gDialect
        #default_schema: geps
logging:
  level:
    org:
      hibernate:
        SQL: ERROR
