server:
  port: 8081
  tomcat:
    uri-encoding: UTF-8
spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    password: 123
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: evan
    #schema: classpath:schema.sql
    #data: classpath:data.sql
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  messages:
    encoding: UTF-8
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    cache: false
  resources:
    static-locations: classpath:/static/
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.Oracle10gDialect
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
